/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCadClientes.java
 *
 * Created on 17/11/2011, 11:19:37
 */
package br.com.ademoc.sgascliente.gui;


import br.com.ademoc.sgas.DomainModel.Cliente;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Deda
 */
public class JFCadClientes extends javax.swing.JFrame {

    private int codigo;
    private boolean id;
    private int hcodigo;
    private int tdcodigo, telcod, emcod;
    private int catcodigo;

    /** Creates new form JFCadClientes */
    public JFCadClientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTCodigoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCSexoCliente = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCEstadoCivil = new javax.swing.JComboBox();
        jCSim = new javax.swing.JCheckBox();
        jCNao = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTMae = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTPai = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jCCategoria = new javax.swing.JComboBox();
        jCDeficiencia = new javax.swing.JComboBox();
        jCAparelho = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jCNDeficiente = new javax.swing.JComboBox();
        jCRendaFamiliar = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jFDataNascCliente = new javax.swing.JFormattedTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTRua = new javax.swing.JTextField();
        jTNumero = new javax.swing.JTextField();
        jTComplemento = new javax.swing.JTextField();
        jTBairro = new javax.swing.JTextField();
        jTCidade = new javax.swing.JTextField();
        jTUf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jCMoradia = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTCep = new javax.swing.JFormattedTextField();
        jTTelefoneResidencial = new javax.swing.JFormattedTextField();
        jTTelefoneCelular = new javax.swing.JFormattedTextField();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTRg = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTOrgaoExpedidor = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTCertNasc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTNaturalidade = new javax.swing.JTextField();
        jTTituloEleitor = new javax.swing.JTextField();
        jTZona = new javax.swing.JTextField();
        jTSecao = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTCnh = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTCategoria = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jFDataExpedicao = new javax.swing.JFormattedTextField();
        jTCpf = new javax.swing.JFormattedTextField();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jCEscolaridade = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jTProfissao = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTHabilidade1 = new javax.swing.JTextField();
        jTHabilidade2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTHabilidade3 = new javax.swing.JTextField();
        jTHabilidade4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObs = new javax.swing.JTextArea();
        jBSalvar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jFDataCadastro = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGAS - Sistema de Gerenciamento de Atendimento Social");
        setIconImages(null);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 1, true), "Cadastro de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setAutoscrolls(true);
        jPanel1.setEnabled(false);

        jDesktopPane1.setBackground(new java.awt.Color(185, 209, 234));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Básicas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jDesktopPane1.setEnabled(false);

        jLabel1.setText("Código");
        jLabel1.setBounds(10, 10, 60, 14);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCodigoCliente.setEditable(false);
        jTCodigoCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTCodigoCliente.setBounds(10, 30, 60, 30);
        jDesktopPane1.add(jTCodigoCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Nome do Cliente");
        jLabel2.setBounds(80, 10, 310, 14);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTNomeCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTNomeCliente.setNextFocusableComponent(jFDataNascCliente);
        jTNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeClienteActionPerformed(evt);
            }
        });
        jTNomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTNomeClienteFocusLost(evt);
            }
        });
        jTNomeCliente.setBounds(80, 30, 340, 30);
        jDesktopPane1.add(jTNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Data Nascimento");
        jLabel3.setBounds(430, 10, 110, 14);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Sexo");
        jLabel4.setBounds(550, 10, 60, 14);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCSexoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino", "" }));
        jCSexoCliente.setNextFocusableComponent(jCEstadoCivil);
        jCSexoCliente.setBounds(550, 30, 90, 30);
        jDesktopPane1.add(jCSexoCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Estado Civil");
        jLabel5.setBounds(640, 10, 100, 20);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viuvo(a)", "Uniao Estável" }));
        jCEstadoCivil.setNextFocusableComponent(jCCategoria);
        jCEstadoCivil.setBounds(650, 30, 100, 30);
        jDesktopPane1.add(jCEstadoCivil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jCSim);
        jCSim.setText("Sim");
        jCSim.setNextFocusableComponent(jCNao);
        jCSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSimActionPerformed(evt);
            }
        });
        jCSim.setBounds(630, 80, 60, 30);
        jDesktopPane1.add(jCSim, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jCNao);
        jCNao.setText("Não");
        jCNao.setNextFocusableComponent(jTMae);
        jCNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNaoActionPerformed(evt);
            }
        });
        jCNao.setBounds(690, 80, 60, 30);
        jDesktopPane1.add(jCNao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Categoria");
        jLabel6.setBounds(10, 60, 170, 14);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Deficiência");
        jLabel7.setBounds(210, 60, 210, 14);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Contribuinte");
        jLabel8.setBounds(630, 60, 110, 14);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTMae.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTMae.setNextFocusableComponent(jTPai);
        jTMae.setBounds(10, 130, 430, 30);
        jDesktopPane1.add(jTMae, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Filiação - Mãe");
        jLabel9.setBounds(10, 110, 310, 14);
        jDesktopPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTPai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTPai.setNextFocusableComponent(jCNDeficiente);
        jTPai.setBounds(10, 180, 430, 30);
        jDesktopPane1.add(jTPai, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel38.setText("Filiação - Pai");
        jLabel38.setBounds(10, 160, 350, 20);
        jDesktopPane1.add(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Deficiente Físico", "Voluntário" }));
        jCCategoria.setNextFocusableComponent(jCDeficiencia);
        jCCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCategoriaActionPerformed(evt);
            }
        });
        jCCategoria.setBounds(10, 80, 190, 30);
        jDesktopPane1.add(jCCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCDeficiencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));
        jCDeficiencia.setNextFocusableComponent(jCAparelho);
        jCDeficiencia.setBounds(210, 80, 230, 30);
        jDesktopPane1.add(jCDeficiencia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCAparelho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Não Utiliza", "Cadeira De Rodas", "Moletas" }));
        jCAparelho.setNextFocusableComponent(jCSim);
        jCAparelho.setBounds(450, 80, 160, 30);
        jDesktopPane1.add(jCAparelho, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel42.setText("Tipo de Aparelho");
        jLabel42.setBounds(450, 60, 150, 14);
        jDesktopPane1.add(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCNDeficiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "" }));
        jCNDeficiente.setNextFocusableComponent(jCRendaFamiliar);
        jCNDeficiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNDeficienteActionPerformed(evt);
            }
        });
        jCNDeficiente.setBounds(450, 150, 120, 30);
        jDesktopPane1.add(jCNDeficiente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCRendaFamiliar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Menos de Um Salário", "Um Salário", "Mais de Um Salário", "" }));
        jCRendaFamiliar.setNextFocusableComponent(jTRua);
        jCRendaFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRendaFamiliarActionPerformed(evt);
            }
        });
        jCRendaFamiliar.setBounds(610, 150, 140, 30);
        jDesktopPane1.add(jCRendaFamiliar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel43.setText("Nº Deficientes na Família");
        jLabel43.setBounds(450, 130, 140, 14);
        jDesktopPane1.add(jLabel43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel44.setText("Renda Familiar");
        jLabel44.setBounds(610, 130, 130, 14);
        jDesktopPane1.add(jLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jFDataNascCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFDataNascCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFDataNascCliente.setNextFocusableComponent(jCSexoCliente);
        jFDataNascCliente.setBounds(430, 30, 110, 30);
        jDesktopPane1.add(jFDataNascCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jDesktopPane2.setEnabled(false);

        jTRua.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTRua.setNextFocusableComponent(jTNumero);
        jTRua.setBounds(10, 40, 220, 30);
        jDesktopPane2.add(jTRua, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTNumero.setNextFocusableComponent(jTComplemento);
        jTNumero.setBounds(240, 40, 40, 30);
        jDesktopPane2.add(jTNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTComplemento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTComplemento.setNextFocusableComponent(jTBairro);
        jTComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTComplementoActionPerformed(evt);
            }
        });
        jTComplemento.setBounds(290, 40, 60, 30);
        jDesktopPane2.add(jTComplemento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTBairro.setNextFocusableComponent(jTCidade);
        jTBairro.setBounds(360, 40, 160, 30);
        jDesktopPane2.add(jTBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCidade.setNextFocusableComponent(jTUf);
        jTCidade.setBounds(530, 40, 160, 30);
        jDesktopPane2.add(jTCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTUf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTUf.setNextFocusableComponent(jTCep);
        jTUf.setBounds(700, 40, 40, 30);
        jDesktopPane2.add(jTUf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("Rua/Av.");
        jLabel10.setBounds(10, 20, 170, 14);
        jDesktopPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("Número");
        jLabel11.setBounds(240, 20, 50, 20);
        jDesktopPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText("Bairro");
        jLabel12.setBounds(360, 20, 90, 14);
        jDesktopPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setText("Compl.");
        jLabel13.setBounds(290, 20, 40, 20);
        jDesktopPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setText("Cidade");
        jLabel14.setBounds(530, 20, 140, 14);
        jDesktopPane2.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setText("UF");
        jLabel15.setBounds(700, 20, 40, 14);
        jDesktopPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setText("CEP");
        jLabel16.setBounds(10, 80, 80, 14);
        jDesktopPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setText("Telefone Residencial");
        jLabel17.setBounds(310, 80, 130, 20);
        jDesktopPane2.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTEmail.setNextFocusableComponent(jTTelefoneResidencial);
        jTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailActionPerformed(evt);
            }
        });
        jTEmail.setBounds(110, 100, 190, 30);
        jDesktopPane2.add(jTEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel37.setText("Email");
        jLabel37.setBounds(110, 80, 170, 20);
        jDesktopPane2.add(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Própria", "Alugada" }));
        jCMoradia.setNextFocusableComponent(jTCpf);
        jCMoradia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMoradiaActionPerformed(evt);
            }
        });
        jCMoradia.setBounds(590, 100, 150, 30);
        jDesktopPane2.add(jCMoradia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel41.setText("Tipo de Moradia");
        jLabel41.setBounds(590, 80, 150, 20);
        jDesktopPane2.add(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setText("Telefone Celular");
        jLabel26.setBounds(450, 80, 130, 14);
        jDesktopPane2.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jTCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTCep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCep.setNextFocusableComponent(jTEmail);
        jTCep.setBounds(10, 100, 90, 30);
        jDesktopPane2.add(jTCep, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jTTelefoneResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTTelefoneResidencial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTTelefoneResidencial.setNextFocusableComponent(jTTelefoneCelular);
        jTTelefoneResidencial.setBounds(310, 100, 130, 30);
        jDesktopPane2.add(jTTelefoneResidencial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jTTelefoneCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTTelefoneCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTTelefoneCelular.setNextFocusableComponent(jCMoradia);
        jTTelefoneCelular.setBounds(450, 100, 130, 30);
        jDesktopPane2.add(jTTelefoneCelular, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(185, 209, 234));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documentos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jDesktopPane3.setEnabled(false);

        jLabel18.setText("CPF");
        jLabel18.setBounds(10, 20, 110, 14);
        jDesktopPane3.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setText("Cart. de Indentidade");
        jLabel19.setBounds(170, 20, 130, 14);
        jDesktopPane3.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTRg.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTRg.setNextFocusableComponent(jTOrgaoExpedidor);
        jTRg.setBounds(170, 40, 110, 30);
        jDesktopPane3.add(jTRg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setText("Orgão Expedidor");
        jLabel20.setBounds(320, 20, 100, 14);
        jDesktopPane3.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTOrgaoExpedidor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTOrgaoExpedidor.setNextFocusableComponent(jFDataExpedicao);
        jTOrgaoExpedidor.setBounds(320, 40, 80, 30);
        jDesktopPane3.add(jTOrgaoExpedidor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setText("Data Expedição");
        jLabel21.setBounds(430, 20, 90, 14);
        jDesktopPane3.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCertNasc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCertNasc.setNextFocusableComponent(jTNaturalidade);
        jTCertNasc.setBounds(10, 100, 120, 30);
        jDesktopPane3.add(jTCertNasc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setText("Cert. Nascimento Nº");
        jLabel23.setBounds(10, 80, 130, 14);
        jDesktopPane3.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setText("Naturalidade");
        jLabel24.setBounds(160, 80, 180, 14);
        jDesktopPane3.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTNaturalidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTNaturalidade.setNextFocusableComponent(jTTituloEleitor);
        jTNaturalidade.setBounds(160, 100, 180, 30);
        jDesktopPane3.add(jTNaturalidade, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTTituloEleitor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTTituloEleitor.setNextFocusableComponent(jTZona);
        jTTituloEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTituloEleitorActionPerformed(evt);
            }
        });
        jTTituloEleitor.setBounds(410, 100, 160, 30);
        jDesktopPane3.add(jTTituloEleitor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTZona.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTZona.setNextFocusableComponent(jTSecao);
        jTZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTZonaActionPerformed(evt);
            }
        });
        jTZona.setBounds(580, 100, 80, 30);
        jDesktopPane3.add(jTZona, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTSecao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTSecao.setNextFocusableComponent(jCEscolaridade);
        jTSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSecaoActionPerformed(evt);
            }
        });
        jTSecao.setBounds(670, 100, 70, 30);
        jDesktopPane3.add(jTSecao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setText("Título de Eleitor Nº");
        jLabel27.setBounds(410, 80, 140, 14);
        jDesktopPane3.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setText("Zona");
        jLabel28.setBounds(580, 80, 70, 14);
        jDesktopPane3.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel29.setText("Seção");
        jLabel29.setBounds(670, 80, 60, 14);
        jDesktopPane3.add(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCnh.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCnh.setNextFocusableComponent(jTCategoria);
        jTCnh.setBounds(540, 40, 110, 30);
        jDesktopPane3.add(jTCnh, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel39.setText("CNH Nº");
        jLabel39.setBounds(540, 20, 90, 14);
        jDesktopPane3.add(jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCategoria.setNextFocusableComponent(jTCertNasc);
        jTCategoria.setBounds(670, 40, 70, 30);
        jDesktopPane3.add(jTCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel40.setText("Cat. CNH");
        jLabel40.setBounds(670, 20, 70, 14);
        jDesktopPane3.add(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jFDataExpedicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFDataExpedicao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFDataExpedicao.setNextFocusableComponent(jTCnh);
        jFDataExpedicao.setBounds(430, 40, 90, 30);
        jDesktopPane3.add(jFDataExpedicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        try {
            jTCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTCpf.setNextFocusableComponent(jTRg);
        jTCpf.setBounds(10, 40, 140, 30);
        jDesktopPane3.add(jTCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBackground(new java.awt.Color(255, 255, 225));
        jDesktopPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formação/Profissão", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jDesktopPane4.setEnabled(false);

        jCEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Primeiro Grau Incompleto", "Primeiro Grau Completo", "Segundo Grau Incompleto", "Segundo Grau Completo", "Terceiro Grau Incompleto", "Terceiro Grau Completo", "Mestrado", "Doutorado", " ", " " }));
        jCEscolaridade.setNextFocusableComponent(jTProfissao);
        jCEscolaridade.setBounds(10, 30, 360, 30);
        jDesktopPane4.add(jCEscolaridade, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setText("Escolaridade");
        jLabel30.setBounds(10, 10, 160, 20);
        jDesktopPane4.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTProfissao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTProfissao.setNextFocusableComponent(jTHabilidade1);
        jTProfissao.setBounds(380, 30, 360, 30);
        jDesktopPane4.add(jTProfissao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setText("Profissão");
        jLabel31.setBounds(530, 10, 90, 20);
        jDesktopPane4.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTHabilidade1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTHabilidade1.setNextFocusableComponent(jTHabilidade2);
        jTHabilidade1.setBounds(10, 80, 360, 30);
        jDesktopPane4.add(jTHabilidade1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTHabilidade2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTHabilidade2.setNextFocusableComponent(jTHabilidade3);
        jTHabilidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHabilidade2ActionPerformed(evt);
            }
        });
        jTHabilidade2.setBounds(380, 80, 360, 30);
        jDesktopPane4.add(jTHabilidade2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel33.setText("Habilidade-1");
        jLabel33.setBounds(10, 60, 190, 20);
        jDesktopPane4.add(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel34.setText("Habilidade -2");
        jLabel34.setBounds(380, 60, 170, 14);
        jDesktopPane4.add(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTHabilidade3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTHabilidade3.setNextFocusableComponent(jTHabilidade4);
        jTHabilidade3.setBounds(10, 130, 360, 30);
        jDesktopPane4.add(jTHabilidade3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTHabilidade4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTHabilidade4.setNextFocusableComponent(jTObs);
        jTHabilidade4.setBounds(380, 130, 360, 30);
        jDesktopPane4.add(jTHabilidade4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel35.setText("Habilidade -3");
        jLabel35.setBounds(10, 110, 190, 14);
        jDesktopPane4.add(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel36.setText("Habilidade -4");
        jLabel36.setBounds(380, 110, 150, 14);
        jDesktopPane4.add(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addComponent(jDesktopPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addComponent(jDesktopPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTObs.setColumns(20);
        jTObs.setRows(5);
        jTObs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jTObs.setNextFocusableComponent(jBSalvar);
        jScrollPane1.setViewportView(jTObs);

        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sgas/gui/save.png"))); // NOI18N
        jBSalvar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALVAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));
        jBSalvar.setNextFocusableComponent(jBExcluir);
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });
        jBSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBSalvarKeyPressed(evt);
            }
        });

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sgas/gui/ExcVagas.png"))); // NOI18N
        jBExcluir.setText("Excluir");
        jBExcluir.setNextFocusableComponent(jBSair);
        jBExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBExcluirKeyPressed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        jBSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBSairKeyPressed(evt);
            }
        });

        jLabel22.setText("Data Cadastro");

        jFDataCadastro.setBackground(new java.awt.Color(227, 227, 227));
        jFDataCadastro.setEditable(false);
        jFDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFDataCadastro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFDataCadastroActionPerformed(evt);
            }
        });

        jLabel25.setText("Usuário");

        jTUsuario.setBackground(new java.awt.Color(227, 227, 227));
        jTUsuario.setEditable(false);
        jTUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)))
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFDataCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBExcluir, jBSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalvar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBExcluir, jBSair});

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1252)/2, (screenSize.height-789)/2, 1252, 789);
    }// </editor-fold>//GEN-END:initComponents

private void jTHabilidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHabilidade2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTHabilidade2ActionPerformed

private void jTTituloEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTituloEleitorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTTituloEleitorActionPerformed

private void jTComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTComplementoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTComplementoActionPerformed

private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

    
    try {

        Cliente c =new Cliente();
        Calendar calendario = Calendar.getInstance();

        jFDataCadastro.setText(new SimpleDateFormat("dd/MM/yyyy").format(calendario.getTime()));
        c.setNome(jTNomeCliente.getText());
        c.setRg(jTRg.getText());
        c.setRgDataExpedicao(new SimpleDateFormat("dd/MM/yyyy").parse(jFDataExpedicao.getText()));
        c.setRgOrgaoExpedidor(jTOrgaoExpedidor.getText());
        c.setCpf(jTCpf.getText());
        c.setTituloEleitor(jTTituloEleitor.getText());
        c.setTituloZona(Integer.parseInt(jTZona.getText()));
        c.setTituloSecao(Integer.parseInt(jTSecao.getText()));
        c.setCnh(jTCnh.getText());
        c.setCategoriaCNH(jTCategoria.getText());
        c.setCertNasc(jTCertNasc.getText());
        c.setQtdDefFamilia(jCNDeficiente.getSelectedIndex() - 1);
        c.setRendaFamiliar(jCRendaFamiliar.getSelectedItem().toString());
        c.setMoradia(jCMoradia.getSelectedItem().toString());
        c.setContribuinte(id);
        c.setEndRua(jTRua.getText());
        c.setEndBairro(jTBairro.getText());
        c.setEndCidade(jTCidade.getText());
        c.setEndEstado(jTUf.getText());
        c.setEndNumero(Integer.parseInt(jTNumero.getText()));
        c.setEndCep(jTCep.getText());
        //c.setComjTComplemento.getText());
        c.setEscolaridade(jCEscolaridade.getSelectedItem().toString());
        c.setEstadoCivil(jCEstadoCivil.getSelectedItem().toString());
        c.setFiliacaoMae(jTMae.getText());
        c.setFiliacaoPai(jTPai.getText());
        c.setDtNasc(new SimpleDateFormat("dd/MM/yyyy").parse(jFDataNascCliente.getText()));
        c.setSexo(jCSexoCliente.getSelectedItem().toString());
        c.setDataCadastro(new SimpleDateFormat("dd/MM/yyyy").parse(jFDataCadastro.getText()));
        c.setObs(jTObs.getText());
        //c.setProfissoes(jTProfissao.get);
        c.setNaturalidade(jTNaturalidade.getText());

       // cat.setDescricao(jCCategoria.getSelectedItem().toString());
       // String teste = cat.getDescricao();
       // catcodigo = retornaCodigoDeficiencia(teste);
        // catcodigo = catDao.cadastrar(cat);
       // c.setCategoria(catcodigo);
       // System.out.println(catcodigo);


       // td.setDescricao(tipo = jCDeficiencia.getSelectedItem().toString());
        //String teste2 = td.getDescricao();
        //tdcodigo = tdDao.cadastrar(td);
        //tdcodigo = retornaCodigoDef(teste2);
        
    } catch (ParseException ex) {

        JOptionPane.showMessageDialog(null, "ERRO AO GRAVAR CLIENTE", "Aviso", JOptionPane.ERROR_MESSAGE);
        //Logger.getLogger(JFCadClientes.class.getName()).log(Level.SEVERE, null, ex);
    }

    JOptionPane.showMessageDialog(null, "Cliente Gravado Com Sucesso", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    // TODO add your handling code here:
}//GEN-LAST:event_jBSalvarActionPerformed

private void jCNDeficienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNDeficienteActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCNDeficienteActionPerformed

private void jCSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSimActionPerformed

    if (jCSim.hasFocus()) {
        id = true;
    }
    // TODO add your handling code here:
}//GEN-LAST:event_jCSimActionPerformed

private void jCNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNaoActionPerformed

    if (jCNao.hasFocus()) {
        id = false;
    }
    // TODO add your handling code here:
}//GEN-LAST:event_jCNaoActionPerformed

private void jTNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeClienteActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTNomeClienteActionPerformed

private void jCCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCategoriaActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jCCategoriaActionPerformed

private void jBSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBSalvarKeyPressed

    jBSalvar.doClick();
    // TODO add your handling code here:
}//GEN-LAST:event_jBSalvarKeyPressed

private void jBExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBExcluirKeyPressed

    jBSair.doClick();
    // TODO add your handling code here:
}//GEN-LAST:event_jBExcluirKeyPressed

private void jBSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBSairKeyPressed

    jBSair.doClick();
    // TODO add your handling code here:
}//GEN-LAST:event_jBSairKeyPressed

private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    jTNomeCliente.requestFocus();

    // TODO add your handling code here:
}//GEN-LAST:event_formWindowGainedFocus

private void jTNomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTNomeClienteFocusLost

    if (jTNomeCliente.getText().equals("")) {

        jTNomeCliente.setBackground(Color.red);
        jTNomeCliente.requestFocus();
        JOptionPane.showMessageDialog(null, "Campo Obrigatorio!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        jTNomeCliente.setBackground(Color.WHITE);

    }

    // TODO add your handling code here:
}//GEN-LAST:event_jTNomeClienteFocusLost

private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed

    setVisible(false);
    // TODO add your handling code here:
}//GEN-LAST:event_jBSairActionPerformed

private void jCRendaFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRendaFamiliarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCRendaFamiliarActionPerformed

private void jTZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTZonaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTZonaActionPerformed

private void jTSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSecaoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTSecaoActionPerformed

private void jFDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFDataCadastroActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jFDataCadastroActionPerformed

private void jTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTEmailActionPerformed

private void jCMoradiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMoradiaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCMoradiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFCadClientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCAparelho;
    private javax.swing.JComboBox jCCategoria;
    private javax.swing.JComboBox jCDeficiencia;
    private javax.swing.JComboBox jCEscolaridade;
    private javax.swing.JComboBox jCEstadoCivil;
    private javax.swing.JComboBox jCMoradia;
    private javax.swing.JComboBox jCNDeficiente;
    private javax.swing.JCheckBox jCNao;
    private javax.swing.JComboBox jCRendaFamiliar;
    private javax.swing.JComboBox jCSexoCliente;
    private javax.swing.JCheckBox jCSim;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JFormattedTextField jFDataCadastro;
    private javax.swing.JFormattedTextField jFDataExpedicao;
    private javax.swing.JFormattedTextField jFDataNascCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCategoria;
    private javax.swing.JFormattedTextField jTCep;
    private javax.swing.JTextField jTCertNasc;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTCnh;
    private javax.swing.JTextField jTCodigoCliente;
    private javax.swing.JTextField jTComplemento;
    private javax.swing.JFormattedTextField jTCpf;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTHabilidade1;
    private javax.swing.JTextField jTHabilidade2;
    private javax.swing.JTextField jTHabilidade3;
    private javax.swing.JTextField jTHabilidade4;
    private javax.swing.JTextField jTMae;
    private javax.swing.JTextField jTNaturalidade;
    private javax.swing.JTextField jTNomeCliente;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextArea jTObs;
    private javax.swing.JTextField jTOrgaoExpedidor;
    private javax.swing.JTextField jTPai;
    private javax.swing.JTextField jTProfissao;
    private javax.swing.JTextField jTRg;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTSecao;
    private javax.swing.JFormattedTextField jTTelefoneCelular;
    private javax.swing.JFormattedTextField jTTelefoneResidencial;
    private javax.swing.JTextField jTTituloEleitor;
    private javax.swing.JTextField jTUf;
    private javax.swing.JTextField jTUsuario;
    private javax.swing.JTextField jTZona;
    // End of variables declaration//GEN-END:variables

     
        
}
