/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Validar.java
 *
 * Created on 25/11/2011, 20:48:03
 */
package br.com.ademoc.sgascliente.gui;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo César
 */
public class ValidarUsuario extends javax.swing.JFrame {
    private String login;
    private String senha;

    /** Creates new form Validar */
    public ValidarUsuario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBAcessar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tLogin = new javax.swing.JTextField();
        tSenha = new javax.swing.JTextField();

        jLabel1.setText("Login:");

        jBAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sgas/gui/user.png"))); // NOI18N
        jBAcessar.setText("Acessar");
        jBAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAcessarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/sgas/gui/logo.png"))); // NOI18N

        jLabel2.setText("Senha:");

        tLogin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tLogin.setNextFocusableComponent(tSenha);

        tSenha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tSenha.setNextFocusableComponent(jBAcessar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jBAcessar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(111, 111, 111)))))
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Validar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAcessarActionPerformed

    
    /*    
    login = tLogin.getText();
    senha = Criptografia.criptografa(tSenha.getText());
    System.out.println(senha);
    
    
    final String sql = ("select * from usuarios where logim=? and senha=?");

    Connection con = null;

    ConectaBanco.setBanco(ConectaBanco.SQLSERVEREXPRESS);
    con = ConectaBanco.getConexao();

    PreparedStatement pstm = null;
    try {
        pstm = con.prepareStatement(sql);
    } catch (SQLException ex) {
        Logger.getLogger(JPanelValidar.class.getName()).log(Level.SEVERE, null, ex);
    }

    Usuario u = new Usuario();
    try {

        pstm.setString(1, login);
    } catch (SQLException ex) {
        Logger.getLogger(JPanelValidar.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        pstm.setString(2, senha);
    } catch (SQLException ex) {
        Logger.getLogger(JPanelValidar.class.getName()).log(Level.SEVERE, null, ex);
    }

    ResultSet rs = null;
    try {
        rs = pstm.executeQuery();
    } catch (SQLException ex) {
        Logger.getLogger(JPanelValidar.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        if (rs.next()) {
            int nivelAcesso = rs.getInt("NIVEL");
            String nome = rs.getString("LOGIM");

            if (nivelAcesso == 1) {   
                JFTelaPrincipal janelaPrincipal = new JFTelaPrincipal();
                janelaPrincipal.setVisible(true);
                this.setVisible(false);
                
                
            } else if (nivelAcesso == 0) { // sem verificação se é igual a outro numero  
                
                JFTelaPrincipal janelaPrincipal = new JFTelaPrincipal();
                janelaPrincipal.setVisible(true); 
                this.setVisible(false);
                
            }

        } else {

            JOptionPane.showMessageDialog(null, "Login ou Senha Invalido!");
            tLogin.setText(null);
            tSenha.setText(null);
            tLogin.requestFocus();

        }
    } catch (SQLException ex) {
        Logger.getLogger(JPanelValidar.class.getName()).log(Level.SEVERE, null, ex);
    }



}//GEN-LAST:event_jBAcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ValidarUsuario().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tLogin;
    private javax.swing.JTextField tSenha;
    // End of variables declaration//GEN-END:variables
 
   
}
